import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

const notoSansKr = Noto_Sans_KR({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['Noto Sans KR', 'Noto Sans KR Fallback', 'Noto Sans KR Fallback Fallback', 'Apple SD Gothic Neo', 'Malgun Gothic', '맑은 고딕', 'sans-serif'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ `${notoSansKr.className}` }>
        {children}
      </body>
    </html>
  );
}
