import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

// 구글 애널리틱스 써드 파티 라이브러리 임포트
import { GoogleAnalytics } from '@next/third-parties/google'

const notoSansKr = Noto_Sans_KR({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['Noto Sans KR', 'Noto Sans KR Fallback', 'Noto Sans KR Fallback Fallback', 'Apple SD Gothic Neo', 'Malgun Gothic', '맑은 고딕', 'sans-serif'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: String(process.env.NEXT_PUBLIC_GOOGLE_SEARCH_ADVISOR_VERTIFICATION), // 구글 서치 어드바이저 환경 변수
    other: {
      'naver-site-verification': String(process.env.NEXT_PUBLIC_NAVAR_SEARCH_ADVISOR_VERTIFICATION), // 네이버 서치 어드바이저 환경 변수
    }
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ `${notoSansKr.className}` }>
        {children}
        {/* 구글 애널리틱스 환경 변수 설정 */}
        {
          process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS && (
            <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
          )
        }
      </body>
    </html>
  );
}
